version: '3.8'
services:
 product_db:
  image: mysql:latest
  restart: always
  environment: 
   MYSQL_DATABASE: 'ProductDB'
   MYSQL_USER: 'user'
   MYSQL_PASSWORD: 'SM@RTcart'
   MYSQL_ROOT_PASSWORD: 'password'
  ports:
   - '3306:3306'
  expose:
   - '3306'
  volumes:
   - my-db:/var/lib/mysql
 cart_db:
  image: mysql:latest
  restart: always
  environment: 
   MYSQL_DATABASE: 'CartDB'
   MYSQL_USER: 'user'
   MYSQL_PASSWORD: 'SM@RTcart'
   MYSQL_ROOT_PASSWORD: 'password'
   MYSQL_TCP_PORT: 3307
  ports:
   - '3307:3307'
  expose:
   - '3307'
  volumes:
   - my-db2:/var/lib/mysql2
 invoice_db:
  image: mysql:latest
  restart: always
  environment: 
   MYSQL_DATABASE: 'InvoiceDB'
   MYSQL_USER: 'user'
   MYSQL_PASSWORD: 'SM@RTcart'
   MYSQL_ROOT_PASSWORD: 'password'
   MYSQL_TCP_PORT: 3308
  ports:
   - '3308:3308'
  expose:
   - '3308'
  volumes:
   - my-db3:/var/lib/mysql3
 account_db:
  image: mysql:latest
  restart: always
  environment: 
   MYSQL_DATABASE: 'AccountDB'
   MYSQL_USER: 'user'
   MYSQL_PASSWORD: 'SM@RTcart'
   MYSQL_ROOT_PASSWORD: 'password'
   MYSQL_TCP_PORT: 3309
  ports:
   - '3309:3309'
  expose:
   - '3309'
  volumes:
   - my-db4:/var/lib/mysql4

volumes:
 my-db:
 my-db2:
 my-db3:
 my-db4: